#! /bin/bash
#Lenox Grayson & Rokhsana Ahmadi


# TEST WEBSITES USED IN ARGS: GOOGLE.COM // NUPEDIA.COM


# date the ping
echo "pinged on: `date` " 
echo

for var1 in "$@"
do
  echo "$var1"
  
  
# isolate packet loss
    packet_loss=$( ping -c3 $var1 |  grep -oP '\d+(?=% packet loss)')


# display packet loss
  echo
  echo "packet loss:"  $packet_loss


# display normal status if packet loss is zero
# display NOT normal status if packet loss is more than zero 

    if [ $packet_loss -eq 0 ]
    then 
          echo "This device is normal"
    else
          echo "This device is NOT normal"
    fi

# send mail to admin if packet loss is more than zero
# tell them to check their inbox
  
  if [ $packet_loss -ne 0 ]
      then 
            echo “Destination $var1 is not reachable!” | mail -s “broken website ” kali@localhost
            echo "Please check your inbox!" 
      fi
done
